name: bundesliga-defender-rumours

on:
  schedule:
    - cron: '30 7 * * *'   # 07:30 UTC daily
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scrape:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.outpath.outputs.path }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scrape Transfermarkt defenders
        env:
          COMPETITION: L1
          SEASON_ID: '2025'
        run: |
          # If your file is NOT in scripts/, change the line below to: python scrape_defenders.py
          python scripts/scrape_defenders.py

      - name: Expose out path
        id: outpath
        run: echo "path=out" >> "$GITHUB_OUTPUT"

  deploy:
    needs: scrape
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ needs.scrape.outputs.artifact-path }}  # uploads 'out/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
